### ISSUE TITLE
[BUG] java8之后的版本易出现非法反射报错

### ISSUE THREAD

**Issue by ziyuan123456789** [lisiwei1/spring-boot-starter-log#5]
在java模块化之后不允许随便反射字段,会产生如下报错:
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.nio.charset.Charset.name accessible: module java.base does not "opens java.nio.charset" to unnamed module @2f465398
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
	at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:20)
	... 35 more

**Comment by lisiwei1** [comment]
好的，收到，我这边会尽快跟进的

**Comment by gotoagain** [comment]
解决了吗，目前只能在jvm添加参数

**Comment by lisiwei1** [comment]
已经新建一个springboot3版本的分支了
